jodconverter:
  local:
    enabled: true
    port-numbers: 2002
    kill-existing-process: true
    process-timeout: 250000
    process-retry-interval: 1000
    max-tasks-per-process: 200
    task-execution-timeout: 250000
    task-queue-timeout: 90000
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages